COMPLETE_CIZ_FACTS = {
    "dagtekening_aanvraag_aanwezig": True,
    "gewenste_zorg_aanwezig": True,
    "achternaam_aanwezig": True,
    "voorletters_aanwezig": True,
    "bsn_aanwezig": True,
    "geboortedatum_aanwezig": True,
    "straat_aanwezig": True,
    "huisnummer_aanwezig": True,
    "postcode_aanwezig": True,
    "woonplaats_aanwezig": True,
    "land_aanwezig": True,
    "land_anders_aanwezig": False,
    "wie_ondertekend": "client",
    "blijvende_fysieke_onmogelijkheid_ondertekenen": False,
    "acute_zorgvraag_ondertekenen_niet_mogelijk": False,
    "aanvraag_vanuit_kloostergemeenschap": False,
    "bevestiging_aanvraag_wettelijke_vertegenwoordiging_aanwezig": False,
    "rechterlijke_machtiging_of_ibs_aanwezig": False,
    "indicatiesteller_zeker_client_kan_overzien": True,
    "eerste_bron_client_kan_overzien": False,
    "tweede_bron_client_kan_overzien": False,
    "machtigingsformulier_aanwezig": False,
    "wie_ondertekende_machtigingsformulier": "client",
    "heeft_gemachtigde_wlz_aanvraag_ondertekend": False,
    "levenstestament_volmacht_of_beschikking_aanwezig": False,
    "indicatiesteller_zeker_machtiging_overzien": False,
    "eerste_bron_machtiging_overzien": False,
    "tweede_bron_machtiging_overzien": False,
    "heeft_gevolmachtigde_wlz_aanvraag_ondertekend": False,
    "medische_informatie_aanwezig": True,
    "dagtekening_informatie_aanwezig": True,
    "diagnosedatum_aanwezig": True,
    "diagnose_handmatig_aanwezig": True,
    "diagnose_nlp_aanwezig": False,
    "diagnose_snomed_gevalideerd": True,
    "informatie_ondertekend_door_ter_zake_kundige": False,
    "stempel_of_logo_aanwezig": True,
    "herleidbaar_document_aanwezig": False,
    "bevoegdheid_ter_zake_kundige": "huisarts",
    "naam_ter_zake_kundige_aanwezig": True,
    "big_nummer_aanwezig": True,
    "agb_code_aanwezig": False,
    "medewerker_acht_ter_zake_kundige_bevoegd": False,
    "naam_zorgverzekeraar": "cz",
    "polisnummer_aanwezig": True,
    "uitzondering_op_verzekering": False,
}

PERSONAL_DATA = {
    "lastName": "De Vries",
    "initials": "A.B.",
    "citizenServiceNumber": "123456782",
    "street": "Voorbeeldstraat",
    "houseNumber": "10A",
    "postalCode": "1234 AB",
    "city": "Utrecht",
    "country": "Nederland",
    "applicantRole": "client",
    "signedBy": "client",
    "authorizationSignedByClient": None,
}


def unique_personal_data():
    import uuid
    return PERSONAL_DATA | {"citizenServiceNumber": f"{uuid.uuid4().int % 1_000_000_000:09d}"}

POSITIVE_MEDICAL_ASSESSMENT = {
    "diagnose_vastgesteld": True,
    "diagnose_door_ter_zake_kundige": True,
    "behandeling_en_effect_beschreven": True,
    "prognose_beschreven": True,
    "blijvende_zorgbehoefte_onderbouwd": True,
    "permanent_toezicht_nodig": True,
    "vierentwintig_uurs_zorg_nabij_nodig": False,
    "medisch_adviseur_nodig": False,
    "medisch_adviseur_geraadpleegd": False,
    "medisch_advies_bevestigt_criteria": False,
    "beoordelingsmotivering": "De gevalideerde bronstukken onderbouwen een blijvende behoefte aan permanent toezicht.",
}
